upsy

diff --git a/.github/workflows/schema_check.yml b/.github/workflows/schema_check.yml
--- a/.github/workflows/schema_check.yml
+++ b/.github/workflows/schema_check.yml
@@ -32,16 +32,16 @@ jobs:
       - name: Wait for PF Workflow completion
         id: wait_for_completion
         run: |
-                echo "Waiting for PF Workflow completion..."
-                while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" https://api.github.com/repos/sheikhasim/graphql-demo-PF/actions/runs/${{ steps.trigger_pf.outputs['event']['data']['id'] }}/check-suite)" != "200" ]]; do
-                  echo "Workflow is still running..."
-                  sleep 10
-                done
-                echo "PF Workflow completed."
+          echo "Waiting for PF Workflow completion..."
+          while [[ "$(curl -s -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" https://api.github.com/repos/sheikhasim/graphql-demo-PF/actions/runs/${{ steps.trigger_pf.outputs.event.data.id }}/workflow-runs | jq -r '.workflow_runs[0].status')" == "in_progress" ]]; do
+            echo "Workflow is still running..."
+            sleep 10
+          done
+          echo "PF Workflow completed."
 
       - name: Check PF Workflow status
         run: |
-                if [[ "$(curl -s -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" https://api.github.com/repos/sheikhasim/graphql-demo-PF/actions/runs/${{ steps.trigger_pf.outputs['event']['data']['id'] }}/check-suite | jq -r .conclusion)" != "success" ]]; then
-                  echo "PF Workflow failed. Exiting..."
-                  exit 1
-                fi
+          if [[ "$(curl -s -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" https://api.github.com/repos/sheikhasim/graphql-demo-PF/actions/runs/${{ steps.trigger_pf.outputs.event.data.id }}/check-suites | jq -r '.check_suites[0].conclusion')" != "success" ]]; then
+            echo "PF Workflow failed. Exiting..."
+            exit 1
+          fi
