upsy

diff --git a/.github/workflows/schema_check_using_API.yml b/.github/workflows/schema_check_using_API.yml
--- a/.github/workflows/schema_check_using_API.yml
+++ b/.github/workflows/schema_check_using_API.yml
@@ -29,20 +29,27 @@ jobs:
         id: api-request
         run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" -D - https://i30fveepxc.execute-api.us-east-1.amazonaws.com/dev)
-          body=$(curl -s https://i30fveepxc.execute-api.us-east-1.amazonaws.com/dev)
+          response_body=$(curl -s https://i30fveepxc.execute-api.us-east-1.amazonaws.com/dev | jq -r '.message')
           echo "::set-output name=response_code::$response"
-          echo "::set-output name=response_body::$body"
-          echo "$response_code"
+          echo "::set-output name=response_body::$response_body"
 
-      # - name: Print API status
-      #   run: |
-      #     response_code=${{ steps.api-request.outputs.response_code }}
-      #     numeric_code=${response_code#* }
-      #     if [ "$numeric_code" -eq 200 ]; then
-      #       echo "API is a success"
-      #     else
-      #       echo "API is a failure"
-      #     fi
+      - name: Print API status
+        run: |
+          response_code=${{ steps.api-request.outputs.response_code }}
+          response_body=${{ steps.api-request.outputs.response_body }}
+
+          if [ "$response_code" -eq 200 ]; then
+            echo "API is a success"
+          else
+            echo "API is a failure"
+            exit 1
+          fi
+
+          echo "Response code: $response_code"
+          echo "Response body: $response_body"
+          
+
+      
 
 
       - name: Dummy Step
